export default[
    {
        id:1,
        name:'Programming',
        icon:'/coding.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health.jpeg',
        prompt:''
    },
    {
        id:3,
        name:'Creative',
        icon:'/creative.png',
        prompt:''
    },
]